import { useState } from "react";
import type { AgentProductId, PluginVersion } from "../../shared/contracts.js";
import { isPhaseOneAgentProductId, type PluginMaterializationView } from "../api.js";
import { AgentBadge } from "./agent-badge.js";
import { agentLabel, sortAgentIds } from "../agent-meta.js";

export type PluginType = "skill" | "mcp"; export type PluginScope = "global" | "project" | "conversation";
export interface InstalledPluginVersion extends PluginVersion { type: PluginType; compatibleAgents: AgentProductId[]; materializations: PluginMaterializationView[]; }
interface Props { installedVersions: InstalledPluginVersion[]; error?: string | null; scope: PluginScope; conversationAgentProductId?: AgentProductId | null; enabledVersions: PluginVersion[]; enablementsLoading?: boolean; language?: "zh" | "en"; onInstallLocalPath(path:string,type:PluginType,agents:AgentProductId[]):void; onPickLocalPath(kind:"directory"|"file"):Promise<string|null>; onRefreshImports():void; onScopeChange(scope:PluginScope):void; onEnableChange(scope:PluginScope, change:PluginVersion & {enabled:boolean}):void; onRepairMaterialization(agent:AgentProductId,plugin:PluginVersion):void; }
const agents: AgentProductId[]=["codex","claude","trae"];
export function PluginSettings(props: Props) {
  const [type,setType]=useState<PluginType>("skill"); const [query,setQuery]=useState(""); const [selectedVersions,setSelectedVersions]=useState<Record<string,string>>({}); const zh=props.language==="zh";
  const installed=groupVersions(props.installedVersions.filter((v)=>v.type===type&&v.pluginId.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())));
  const choose=async()=>{ const path=await props.onPickLocalPath(type==="skill"?"directory":"file"); if(path) props.onInstallLocalPath(path,type,type==="skill"?agents:[]); };
  return <section className="plugin-settings" aria-label="Plugin settings">
    <div className="plugin-settings__heading"><div><h1>{zh?"插件":"Plugins"}</h1><p>{zh?"已自动发现本机 Skills 与 MCP。开关决定它们是否在所选范围生效；只有添加其他位置时才需要选择文件。":"Installed Skills and MCP are automatically discovered. Use the switch for the selected scope; choose a file only to add another location."}</p></div><button type="button" onClick={props.onRefreshImports}>{zh?"自动导入":"Auto import"}</button></div>
    {props.error?<p role="alert">{zh?"插件清单不可用":"Plugin inventory unavailable"}: {props.error}</p>:null}
    <div className="plugin-settings__tabs" role="group" aria-label="Plugin types"><button type="button" data-active={type==="skill"} onClick={()=>setType("skill")}>Skills</button><button type="button" data-active={type==="mcp"} onClick={()=>setType("mcp")}>MCP</button></div>
    <div className="plugin-settings__toolbar"><label>{zh?"生效范围":"Apply to"}<select aria-label="Plugin scope" value={props.scope} onChange={(e)=>props.onScopeChange(e.currentTarget.value as PluginScope)}><option value="global">{zh?"所有项目":"All projects"}</option><option value="project">{zh?"当前项目":"Current project"}</option><option value="conversation">{zh?"当前对话":"Current conversation"}</option></select></label><input type="search" aria-label="Search plugins" placeholder={zh?"搜索插件":"Search plugins"} value={query} onChange={(event)=>setQuery(event.currentTarget.value)}/><button type="button" onClick={()=>void choose()}>{type==="skill"?(zh?"添加 Skill":"Add Skill"):(zh?"添加 MCP":"Add MCP")}</button></div>
    <PluginList title={zh?"可用插件":"Available plugins"} ariaLabel="Installed plugin versions" empty={zh?"没有匹配的插件":"No matching plugins"} rows={installed.map((versions)=>{
      const enabledVersion=props.enabledVersions.find((item)=>item.pluginId===versions[0]!.pluginId)?.versionId;
      const v=versions.find((item)=>item.versionId===(selectedVersions[versions[0]!.pluginId]??enabledVersion))??versions[0]!;
      const enabled=props.enabledVersions.some((e)=>e.pluginId===v.pluginId&&e.versionId===v.versionId);
      const compatible=sortAgentIds(v.compatibleAgents.filter(isPhaseOneAgentProductId));
      const incompatible=!compatible.length||(props.scope==="conversation"&&props.conversationAgentProductId!=null&&!compatible.includes(props.conversationAgentProductId));
      return {key:v.pluginId,name:v.pluginId,kind:v.type==="skill"?"Skill":"MCP",version:versions.length===1?<span className="plugin-settings__version">{short(v.versionId)}</span>:<select className="plugin-settings__version-select" aria-label={`Version for ${v.pluginId}`} value={v.versionId} onChange={(event)=>{const versionId=event.currentTarget.value;setSelectedVersions((current)=>({...current,[v.pluginId]:versionId}));if(enabled)props.onEnableChange(props.scope,{pluginId:v.pluginId,versionId,enabled:true});}}>{versions.map((item)=><option key={item.versionId} value={item.versionId}>{short(item.versionId)}</option>)}</select>,action:<label className="plugin-settings__switch"><input type="checkbox" aria-label={`Enable ${v.pluginId} ${v.versionId}`} disabled={props.enablementsLoading||(!enabled&&incompatible)} checked={enabled} onChange={(e)=>props.onEnableChange(props.scope,{pluginId:v.pluginId,versionId:v.versionId,enabled:e.currentTarget.checked})}/><span aria-hidden="true"/></label>,agents:<>{compatible.map((agent)=><AgentBadge key={agent} agent={agent}/>)}</>,repairs:<>{compatible.flatMap((agent)=>{const materialization=v.materializations.find((item)=>item.agentProductId===agent);return materialization?.repairable?[<button type="button" key={agent} aria-label={`Repair ${v.pluginId} ${v.versionId} for ${agentLabel(agent)}`} onClick={()=>props.onRepairMaterialization(agent,v)}>{zh?`修复 ${agentLabel(agent)}`:`Repair ${agentLabel(agent)}`}</button>]:[];})}</>};
    })}/>
  </section>;
}
function PluginList({title,ariaLabel,empty,rows}:{title:string;ariaLabel:string;empty:string;rows:Array<{key:string;name:string;kind:string;version:React.ReactNode;action:React.ReactNode;agents:React.ReactNode;repairs:React.ReactNode}>}) { return <section aria-label={ariaLabel} className="plugin-settings__section"><h2>{title}<span>{rows.length}</span></h2>{rows.length?<ul className="plugin-settings__list">{rows.map((row)=><li key={row.key}><div className="plugin-settings__card"><div className="plugin-settings__name"><span className="plugin-settings__kind">{row.kind}</span><strong>{row.name}</strong></div>{row.version}<div className="plugin-settings__agents">{row.agents}</div><div className="plugin-settings__repairs">{row.repairs}</div></div>{row.action}</li>)}</ul>:<p className="plugin-settings__empty">{empty}</p>}</section>; }
function groupVersions(versions:InstalledPluginVersion[]):InstalledPluginVersion[][]{const groups=new Map<string,InstalledPluginVersion[]>();for(const version of versions){const group=groups.get(version.pluginId)??[];group.push(version);groups.set(version.pluginId,group);}return [...groups.values()].map((group)=>group.sort((a,b)=>b.versionId.localeCompare(a.versionId))).sort((a,b)=>a[0]!.pluginId.localeCompare(b[0]!.pluginId));}
function short(value:string){return value.length>12?`${value.slice(0,12)}…`:value;}
