import { useEffect, useState } from "react";
import type { GraphProject } from "../../shared/contracts.js";
import type { ConversationView, ProjectView } from "../api.js";
import { AgentBadge } from "./agent-badge.js";

interface ProjectSidebarProps {
  projects: ProjectView[]; conversations: ConversationView[]; graphs?: GraphProject[]; selectedProjectId: string | null; selectedConversationId: string | null; selectedGraphId?: string | null;
  onOpenProject(): Promise<void>; onRestartWorkspace(): Promise<void>; onCreateConversation(): void; onCreateGraph?(): void; onSelectProject(id: string): void; onSelectConversation(id: string): void; onSelectGraph?(id: string): void; onOpenSettings(): void;
  onRenameProject?(id: string, name: string): Promise<void>; onArchiveProject?(id: string): Promise<void>; onRenameConversation?(id: string, title: string): Promise<void>; onArchiveConversation?(id: string): Promise<void>; onForkConversation?(id: string): Promise<void>;
  collapsed: boolean; onToggleCollapsed(): void; language?: "zh" | "en";
  unreadConversationIds?: ReadonlySet<string>;
}

export function ProjectSidebar(props: ProjectSidebarProps) {
  const zh = props.language === "zh";
  const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(""); const [menu, setMenu] = useState<string | null>(null);
  const [collapsedProjects, setCollapsedProjects] = useState<Set<string>>(() => new Set());
  const [opening, setOpening] = useState(false);
  const [restarting, setRestarting] = useState(false);
  const [rename, setRename] = useState<{ kind: "project" | "conversation"; id: string; value: string } | null>(null);
  const matches = (value: string) => value.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
  useEffect(() => {
    if (!menu) return;
    const closeOutside = (event: PointerEvent): void => {
      const target = event.target;
      if (!(target instanceof Element) || !target.closest(".project-sidebar__menu, .project-sidebar__more")) {
        setMenu(null);
      }
    };
    document.addEventListener("pointerdown", closeOutside);
    return () => document.removeEventListener("pointerdown", closeOutside);
  }, [menu]);

  return <nav className="project-sidebar" aria-label={zh ? "项目与对话" : "Projects and conversations"}>
    <div className="project-sidebar__brand"><span className="project-sidebar__logo">A1</span><strong>Ain One</strong><button type="button" aria-label={props.collapsed ? (zh ? "展开侧栏" : "Expand sidebar") : (zh ? "收起侧栏" : "Collapse sidebar")} onClick={props.onToggleCollapsed}>{props.collapsed ? "›" : "‹"}</button></div>
    <div className="project-sidebar__create-actions"><button type="button" className="project-sidebar__new" aria-label={zh ? "新对话" : "New chat"} disabled={!props.selectedProjectId} onClick={props.onCreateConversation}>＋ {!props.collapsed ? <span>{zh ? "新对话" : "New chat"}</span> : null}</button><button type="button" className="project-sidebar__new" aria-label={zh ? "新建图" : "New graph"} disabled={!props.selectedProjectId} onClick={props.onCreateGraph}>◇ {!props.collapsed ? <span>{zh ? "新建图" : "New graph"}</span> : null}</button></div>
    <div className="project-sidebar__workspace-heading"><h2>{zh ? "工作区" : "Workspace"}</h2><div>{opening ? <span className="project-sidebar__opening" role="status">{zh ? "正在打开…" : "Opening…"}</span> : null}<button type="button" data-tooltip={zh ? "重启工作区" : "Restart workspace"} data-tooltip-side="bottom" aria-label={zh ? "重启工作区" : "Restart workspace"} aria-busy={restarting} disabled={restarting} onClick={() => { setRestarting(true); void props.onRestartWorkspace().finally(() => setRestarting(false)); }}>{restarting ? <span className="project-sidebar__spinner" aria-hidden="true" /> : <RestartIcon />}</button><button type="button" data-tooltip={zh ? "搜索工作区" : "Search workspace"} data-tooltip-side="bottom" aria-label={zh ? "搜索工作区" : "Search workspace"} onClick={() => setSearchOpen((v) => !v)}><SearchIcon /></button><button type="button" data-tooltip={zh ? "新建项目" : "New project"} data-tooltip-side="bottom" aria-label={opening ? (zh ? "正在打开项目文件夹" : "Opening Project Folder") : (zh ? "打开项目文件夹" : "Open Project Folder")} aria-busy={opening} disabled={opening} onClick={() => { setOpening(true); void props.onOpenProject().finally(() => setOpening(false)); }}>{opening ? <span className="project-sidebar__spinner" aria-hidden="true" /> : <PlusIcon />}</button></div></div>
    {searchOpen ? <div className="project-sidebar__search"><input autoFocus aria-label={zh ? "搜索项目、图与对话" : "Search projects, graphs, and chats"} value={query} onChange={(event) => setQuery(event.currentTarget.value)} placeholder={zh ? "搜索项目、图与对话" : "Search projects, graphs, and chats"}/>{query ? <button type="button" aria-label={zh ? "清除搜索" : "Clear search"} onClick={() => setQuery("")}>×</button> : null}</div> : null}
    <ul className="project-sidebar__project-list">{props.projects.map((project) => { const graphs = (props.graphs ?? []).filter((item) => item.projectId === project.id && (!query || matches(item.name))).sort((left, right) => right.updatedAt.localeCompare(left.updatedAt)); const conversations = props.conversations.filter((item) => item.projectId === project.id && (!query || matches(item.title))).sort((left, right) => (right.lastTurnAt ?? "").localeCompare(left.lastTurnAt ?? "")); const expanded = Boolean(query) || !collapsedProjects.has(project.id); if (query && !matches(project.name) && !graphs.length && !conversations.length) return null; return <li key={project.id} className="project-sidebar__project-item">
      <div className="project-sidebar__row"><button type="button" className="project-sidebar__project-button" data-active={props.selectedProjectId === project.id} aria-pressed={props.selectedProjectId === project.id} aria-expanded={expanded} onClick={() => { if (props.selectedProjectId !== project.id) { props.onSelectProject(project.id); setCollapsedProjects((current) => { const next = new Set(current); next.delete(project.id); return next; }); } else { setCollapsedProjects((current) => { const next = new Set(current); if (next.has(project.id)) next.delete(project.id); else next.add(project.id); return next; }); } }}><ProjectChevron /><span>{project.name}</span></button><button type="button" className="project-sidebar__more" aria-label={`${zh ? "管理项目" : "Manage project"} ${project.name}`} onClick={() => setMenu(menu === `p:${project.id}` ? null : `p:${project.id}`)}>•••</button>{menu === `p:${project.id}` ? <div className="project-sidebar__menu"><button type="button" onClick={() => { setRename({ kind: "project", id: project.id, value: project.name }); setMenu(null); }}>{zh ? "重命名项目" : "Rename project"}</button><button type="button" onClick={() => { void props.onArchiveProject?.(project.id); setMenu(null); }}>{zh ? "归档项目" : "Archive project"}</button></div> : null}</div>
      {expanded ? <div className="project-sidebar__resources"><section role="group" aria-label={zh ? "图" : "Graph"}><h3>{zh ? "图" : "Graph"}</h3><ul className="project-sidebar__resource-list">{graphs.map((graph) => <li key={graph.id}><button type="button" className="project-sidebar__resource-button" data-active={props.selectedGraphId === graph.id} aria-pressed={props.selectedGraphId === graph.id} aria-label={graph.name} onClick={() => props.onSelectGraph?.(graph.id)}><span>{graph.name}</span></button></li>)}</ul></section><section role="group" aria-label={zh ? "对话" : "Chat"}><h3>{zh ? "对话" : "Chat"}</h3><ul className="project-sidebar__resource-list">{conversations.map((conversation) => <li key={conversation.id}><div className="project-sidebar__row"><button type="button" className="project-sidebar__resource-button" data-active={props.selectedConversationId === conversation.id} aria-pressed={props.selectedConversationId === conversation.id} aria-label={conversation.title} onClick={() => props.onSelectConversation(conversation.id)}><span>{conversation.title}</span><span className="project-sidebar__badges"><span aria-hidden="true"><AgentBadge agent={conversation.agentProductId}/></span>{props.unreadConversationIds?.has(conversation.id) ? <span className="project-sidebar__badge" aria-label={zh ? "未读" : "Unread"} /> : null}</span></button><button type="button" className="project-sidebar__more" aria-label={(zh ? "管理会话 " : "Manage conversation ") + conversation.title} onClick={() => setMenu(menu === `c:${conversation.id}` ? null : `c:${conversation.id}`)}>•••</button>{menu === `c:${conversation.id}` ? <div className="project-sidebar__menu"><button type="button" onClick={() => { setRename({ kind: "conversation", id: conversation.id, value: conversation.title }); setMenu(null); }}>{zh ? "重命名" : "Rename"}</button><button type="button" onClick={() => { void props.onForkConversation?.(conversation.id); setMenu(null); }}>{zh ? "分叉会话" : "Branch conversation"}</button><button type="button" onClick={() => { void props.onArchiveConversation?.(conversation.id); setMenu(null); }}>{zh ? "归档会话" : "Archive conversation"}</button></div> : null}</div></li>)}</ul></section></div> : null}
    </li>; })}</ul>
    <div className="project-sidebar__footer"><button type="button" aria-label={zh ? "设置" : "Settings"} onClick={props.onOpenSettings}><SettingsIcon />{!props.collapsed ? <span>{zh ? "设置" : "Settings"}</span> : null}</button></div>
    {rename ? <div className="client-dialog"><button type="button" className="client-dialog__backdrop" aria-label={zh ? "取消重命名" : "Cancel rename"} onPointerDown={() => setRename(null)}/><form className="client-dialog__panel" role="dialog" aria-modal="true" aria-label={rename.kind === "project" ? (zh ? "重命名项目" : "Rename project") : (zh ? "重命名会话" : "Rename conversation")} onSubmit={(event) => { event.preventDefault(); const value = rename.value.trim(); if (!value) return; const action = rename.kind === "project" ? props.onRenameProject?.(rename.id, value) : props.onRenameConversation?.(rename.id, value); setRename(null); void action; }}><h2>{rename.kind === "project" ? (zh ? "重命名项目" : "Rename project") : (zh ? "重命名会话" : "Rename conversation")}</h2><input autoFocus value={rename.value} onChange={(event) => setRename({ ...rename, value: event.currentTarget.value })}/><div><button type="button" onClick={() => setRename(null)}>{zh ? "取消" : "Cancel"}</button><button type="submit">{zh ? "保存" : "Save"}</button></div></form></div> : null}
  </nav>;
}

function SearchIcon() { return <svg viewBox="0 0 20 20" aria-hidden="true"><circle cx="8.5" cy="8.5" r="4.5"/><path d="m12 12 4 4"/></svg>; }
function PlusIcon() { return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M10 4v12M4 10h12"/></svg>; }
function RestartIcon() { return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M15.4 7.2A6 6 0 1 0 16 11"/><path d="M15.5 3.8v3.8h-3.8"/></svg>; }
function ProjectChevron() { return <svg className="project-sidebar__chevron" viewBox="0 0 16 16" aria-hidden="true"><path d="m4.5 6 3.5 3.5L11.5 6" /></svg>; }
function SettingsIcon() { return <svg viewBox="0 0 20 20" aria-hidden="true"><circle cx="10" cy="10" r="3"/><path d="M10 2.5v2M10 15.5v2M2.5 10h2M15.5 10h2M4.7 4.7l1.4 1.4M13.9 13.9l1.4 1.4M15.3 4.7l-1.4 1.4M6.1 13.9l-1.4 1.4"/></svg>; }
